import { ModuleDescriptor, FunctionDescriptor, ParameterDescriptor } from "./types";

const buildParams = (count: number): ParameterDescriptor[] => {
    const params: ParameterDescriptor[] = [];
    for (let i = 0; i < count; i++) {
        params.push({ name: `arg${i}`, type: "u32" });
    }
    return params;
};

const makeFunc = (name: string, argCount: number, overrides: Partial<FunctionDescriptor> = {}): FunctionDescriptor => ({
    name,
    params: overrides.params ?? buildParams(argCount),
    returnType: overrides.returnType ?? "u32",
    callingConvention: overrides.callingConvention ?? "stdcall",
});

export const gdi32Module: ModuleDescriptor = {
    name: "gdi32",
    functions: [
        makeFunc("GetStockObject", 1),
        makeFunc("TextOut", 5),
        makeFunc("SetBkMode", 2),
        makeFunc("SetTextColor", 2),
        makeFunc("CreateSolidBrush", 1),
        makeFunc("CreatePatternBrush", 1),
        makeFunc("SelectObject", 2),
        makeFunc("DeleteObject", 1),
        makeFunc("Rectangle", 5),
        makeFunc("Ellipse", 5),
        makeFunc("MoveToEx", 4),
        makeFunc("LineTo", 3),
        makeFunc("CreatePen", 3),
        makeFunc("CreateFontIndirect", 1),
        makeFunc("GetDeviceCaps", 2),
        makeFunc("ChoosePixelFormat", 2),
        makeFunc("SetPixelFormat", 3),
        makeFunc("DescribePixelFormat", 4),
        makeFunc("GetPixelFormat", 1),
        makeFunc("SwapBuffers", 1),
        makeFunc("SetDeviceGammaRamp", 2),
        makeFunc("GetDeviceGammaRamp", 2),
        makeFunc("GdiSetBatchLimit", 1),
        makeFunc("SetBkColor", 2),
        makeFunc("GetTextExtentPoint32", 4),
        makeFunc("CreateFontA", 14),
        makeFunc("CreateFontW", 14),
        makeFunc("CreateFontIndirectW", 1),
        makeFunc("TextOutW", 5),
        makeFunc("DeleteDC", 1),
        makeFunc("CreateCompatibleDC", 1),
        makeFunc("GetObjectA", 3),
        makeFunc("GetObjectW", 3),
        makeFunc("GetPixel", 3),
        makeFunc("StretchBlt", 11),
        makeFunc("BitBlt", 9),
        makeFunc("GetDIBits", 7),
        makeFunc("GetDIBColorTable", 4),
        makeFunc("SetPixel", 4),
        makeFunc("SetStretchBltMode", 2),
        makeFunc("PatBlt", 6),
        makeFunc("CreatePalette", 1),
        makeFunc("SelectPalette", 3),
        makeFunc("RealizePalette", 1),
        makeFunc("GetSystemPaletteUse", 1),
        makeFunc("GetSystemPaletteEntries", 4),
        makeFunc("CreateCompatibleBitmap", 3),
        makeFunc("StretchDIBits", 13),
        makeFunc("CreateDIBSection", 6),
        makeFunc("SetDIBitsToDevice", 12),

        // Text and font metrics
        makeFunc("GetTextMetricsA", 2),
        makeFunc("GetTextMetricsW", 2),
        makeFunc("GetTextExtentPointA", 4),
        makeFunc("GetTextExtentExPointA", 7),
        makeFunc("GetCharWidthA", 4),
        makeFunc("ExtTextOutA", 8),

        // Bitmap creation
        makeFunc("CreateDIBitmap", 6),
        makeFunc("CreateBitmap", 5),

        // Device context management
        makeFunc("CreateDCA", 4),
        makeFunc("CreateICA", 4),
        makeFunc("SaveDC", 1),
        makeFunc("RestoreDC", 2),
        makeFunc("GetCurrentObject", 2),

        // Coordinate transformations
        makeFunc("SetMapMode", 2),
        makeFunc("SetViewportOrgEx", 4),
        makeFunc("SetViewportExtEx", 4),
        makeFunc("SetWindowExtEx", 4),
        makeFunc("OffsetViewportOrgEx", 4),
        makeFunc("ScaleViewportExtEx", 6),
        makeFunc("ScaleWindowExtEx", 6),
        makeFunc("DPtoLP", 3),

        // Clipping and visibility
        makeFunc("GetClipBox", 2),
        makeFunc("IntersectClipRect", 5),
        makeFunc("ExcludeClipRect", 5),
        makeFunc("PtVisible", 3),
        makeFunc("RectVisible", 2),

        // Printing support
        makeFunc("StartDocA", 2),
        makeFunc("EndDoc", 1),
        makeFunc("AbortDoc", 1),
        makeFunc("StartPage", 1),
        makeFunc("EndPage", 1),
        makeFunc("SetAbortProc", 2),
        makeFunc("Escape", 5),
        // Additional GDI imports seen in modern compatibility layers
        makeFunc("GetRandomRgn", 3),
        makeFunc("SetPaletteEntries", 4),
        makeFunc("ResizePalette", 2),
        makeFunc("GetRegionData", 3),
        makeFunc("ExtCreateRegion", 3),
        makeFunc("D3DKMTSetQueuedLimit", 1),
        makeFunc("D3DKMTGetScanLine", 1),
        makeFunc("D3DKMTCreateDCFromMemory", 1),
        makeFunc("D3DKMTSetGammaRamp", 1),
        makeFunc("D3DKMTSetVidPnSourceOwner", 1),
        makeFunc("D3DKMTCloseAdapter", 1),
        makeFunc("D3DKMTOpenAdapterFromHdc", 1),
        makeFunc("D3DKMTQueryAdapterInfo", 1),
        makeFunc("D3DKMTPresent", 1),
        makeFunc("D3DKMTCreateDevice", 1),
        makeFunc("D3DKMTReleaseProcessVidPnSourceOwners", 1),
        makeFunc("GetViewportExtEx", 2),
        makeFunc("GetViewportOrgEx", 2),
        makeFunc("GetWindowExtEx", 2),
        makeFunc("GetWindowOrgEx", 2),
        makeFunc("SelectClipRgn", 2),
        makeFunc("ExtSelectClipRgn", 3),
        makeFunc("SetMetaRgn", 1),
        makeFunc("SetDCBrushColor", 2),
        makeFunc("SetDCPenColor", 2),
        makeFunc("SetGraphicsMode", 2),
        makeFunc("SetLayout", 2),
        makeFunc("GetLayout", 1),
        makeFunc("SetPolyFillMode", 2),
        makeFunc("SetROP2", 2),
        makeFunc("SetTextCharacterExtra", 2),
        makeFunc("SetTextAlign", 2),
        makeFunc("GetWorldTransform", 2),
        makeFunc("SetWorldTransform", 2),
        makeFunc("ModifyWorldTransform", 3),
        makeFunc("SetArcDirection", 2),
        makeFunc("GetArcDirection", 1),
        makeFunc("SetWindowOrgEx", 4),
        makeFunc("SetBrushOrgEx", 4),
        makeFunc("GetObjectType", 1),
        makeFunc("Arc", 9),
        makeFunc("Chord", 9),
        makeFunc("CreateBitmapIndirect", 1),
        makeFunc("CreateDiscardableBitmap", 3),
        makeFunc("DrawEscape", 5),
        makeFunc("ExtFloodFill", 5),
        makeFunc("FillRgn", 3),
        makeFunc("FrameRgn", 5),
        makeFunc("InvertRgn", 2),
        makeFunc("MaskBlt", 13),
        makeFunc("PlgBlt", 11),
        makeFunc("Pie", 9),
        makeFunc("PaintRgn", 2),
        makeFunc("PolyPolygon", 3),
        makeFunc("RoundRect", 7),
        makeFunc("GetBitmapBits", 3),
        makeFunc("SetBitmapBits", 3),
        makeFunc("SetDIBits", 7),
        makeFunc("SetPixelV", 4),
        makeFunc("GdiAlphaBlend", 11),
        makeFunc("GdiTransparentBlt", 11),
        makeFunc("GdiGradientFill", 6),
        makeFunc("AngleArc", 6),
        makeFunc("PolyPolyline", 3),
        makeFunc("ArcTo", 9),
        makeFunc("PolyDraw", 3),
        makeFunc("ExtTextOutW", 8),
        makeFunc("PolyTextOutA", 3),
        makeFunc("PolyTextOutW", 3),
        makeFunc("LPtoDP", 3),
        makeFunc("Polygon", 3),
        makeFunc("Polyline", 3),
        makeFunc("PolyBezier", 3),
        makeFunc("PolyBezierTo", 3),
        makeFunc("PolylineTo", 3),
        makeFunc("GetPaletteEntries", 4),
        makeFunc("GetNearestPaletteIndex", 2),
        makeFunc("SetSystemPaletteUse", 2),
        makeFunc("UnrealizeObject", 1),
        makeFunc("CombineRgn", 4),
        makeFunc("CreateRectRgn", 4),
        makeFunc("CreateRectRgnIndirect", 1),
        makeFunc("CreateRoundRectRgn", 6),
        makeFunc("CreateEllipticRgn", 4),
        makeFunc("CreatePolygonRgn", 3),
        makeFunc("GetRgnBox", 2),
        makeFunc("SetDIBColorTable", 4),
        makeFunc("OffsetRgn", 3),
        makeFunc("GetROP2", 1),
        makeFunc("GetBkColor", 1),
        makeFunc("GetDCBrushColor", 1),
        makeFunc("GetDCPenColor", 1),
        makeFunc("GetBkMode", 1),
        makeFunc("GetBrushOrgEx", 2),
        makeFunc("GetClipRgn", 2),
        makeFunc("GetCurrentPositionEx", 2),
        makeFunc("GetGraphicsMode", 1),
        makeFunc("GetMapMode", 1),
        makeFunc("GetPolyFillMode", 1),
        makeFunc("GetStretchBltMode", 1),
        makeFunc("GetTextCharacterExtra", 1),
        makeFunc("GetTextAlign", 1),
        makeFunc("GetTextColor", 1),
        makeFunc("GetDCOrgEx", 2),
        makeFunc("GdiFlush", 0),
        makeFunc("RectInRegion", 2),
        makeFunc("GetCharABCWidthsA", 4),
        makeFunc("GetCharABCWidthsW", 4),

        // Auto-generated from reference signatures
        makeFunc("CreateBrushIndirect", 1),
        makeFunc("CreateColorSpaceA", 1),
        makeFunc("CreateColorSpaceW", 1),
        makeFunc("CreateDCW", 4),
        makeFunc("CreateDIBPatternBrush", 2),
        makeFunc("CreateDIBPatternBrushPt", 2),
        makeFunc("CreateEllipticRgnIndirect", 1),
        makeFunc("CreateEnhMetaFileA", 4),
        makeFunc("CreateEnhMetaFileW", 4),
        makeFunc("CreateFontIndirectA", 1),
        makeFunc("CreateFontIndirectExA", 1),
        makeFunc("CreateFontIndirectExW", 1),
        makeFunc("CreateHalftonePalette", 1),
        makeFunc("CreateHatchBrush", 2),
        makeFunc("CreateICW", 4),
        makeFunc("CreateMetaFileA", 1),
        makeFunc("CreateMetaFileW", 1),
        makeFunc("CreatePenIndirect", 1),
        makeFunc("CreateScalableFontResourceA", 4),
        makeFunc("CreateScalableFontResourceW", 4),
        makeFunc("AddFontResourceA", 1),
        makeFunc("RemoveFontResourceA", 1),
        makeFunc("DeleteColorSpace", 1),
        makeFunc("DeleteEnhMetaFile", 1),
        makeFunc("DeleteMetaFile", 1),
        makeFunc("GetTextCharset", 1),
        makeFunc("GetTextCharsetInfo", 3),
        makeFunc("SelectClipPath", 2),
        // GDI path bracket (BeginPath .. EndPath, then one of the render verbs)
        makeFunc("BeginPath", 1),
        makeFunc("EndPath", 1),
        makeFunc("AbortPath", 1),
        makeFunc("CloseFigure", 1),
        makeFunc("FillPath", 1),
        makeFunc("StrokePath", 1),
        makeFunc("StrokeAndFillPath", 1),
        makeFunc("FlattenPath", 1),
        makeFunc("WidenPath", 1),
        makeFunc("PathToRegion", 1),
        makeFunc("GetPath", 4),
        makeFunc("SelectVisRgn", 2),
        makeFunc("SetTextJustification", 3),

        // Font enumeration, metafiles, pens, and misc GDI
        makeFunc("EnumFontFamiliesA", 4),
        makeFunc("EnumFontFamiliesExA", 5),
        makeFunc("GetTextFaceA", 3),
        makeFunc("GetNearestColor", 2),
        makeFunc("ExtCreatePen", 5),
        makeFunc("CloseMetaFile", 1),
        makeFunc("CopyMetaFileA", 2),
        makeFunc("PlayMetaFile", 2),
        makeFunc("EnumMetaFile", 4),
        makeFunc("PlayMetaFileRecord", 4),
        makeFunc("SetColorAdjustment", 2),
        makeFunc("SetMapperFlags", 2),
        makeFunc("OffsetClipRgn", 3),
        makeFunc("OffsetWindowOrgEx", 4),
        makeFunc("SetRectRgn", 5),

        // ICM / color management
        makeFunc("GetICMProfileW", 3),
    ]
};
