import { ModuleDescriptor, FunctionDescriptor, ParameterDescriptor } from "./types";

const buildParams = (count: number): ParameterDescriptor[] => {
    const params: ParameterDescriptor[] = [];
    for (let i = 0; i < count; i++) {
        params.push({ name: `arg${i}`, type: "u32" });
    }
    return params;
};

const makeFunc = (name: string, argCount: number, overrides: Partial<FunctionDescriptor> = {}): FunctionDescriptor => ({
    name,
    params: overrides.params ?? buildParams(argCount),
    returnType: overrides.returnType ?? "u32",
    callingConvention: overrides.callingConvention ?? "stdcall",
});

export const user32Module: ModuleDescriptor = {
    name: "user32",
    functions: [
        makeFunc("RegisterClassExA", 1),
        makeFunc("RegisterClassExW", 1),
        makeFunc("RegisterClassA", 1),
        makeFunc("RegisterClassW", 1),
        makeFunc("CreateWindowExA", 12),
        makeFunc("CreateWindowExW", 12),
        makeFunc("CreateWindowA", 11),
        makeFunc("CreateWindowW", 11),
        makeFunc("ShowWindow", 2),
        makeFunc("UpdateWindow", 1),
        makeFunc("GetMessageA", 4),
        makeFunc("GetMessageW", 4),
        makeFunc("TranslateMessage", 1),
        makeFunc("DispatchMessageA", 1),
        makeFunc("DispatchMessageW", 1),
        makeFunc("PostQuitMessage", 1),
        makeFunc("DefWindowProcA", 4),
        makeFunc("DefWindowProcW", 4),
        makeFunc("LoadCursorA", 2),
        makeFunc("LoadCursorW", 2),
        makeFunc("LoadIconA", 2),
        makeFunc("LoadIconW", 2),
        makeFunc("MessageBoxA", 4),
        makeFunc("MessageBoxW", 4),
        makeFunc("BeginPaint", 2),
        makeFunc("EndPaint", 2),
        makeFunc("DestroyWindow", 1),
        makeFunc("GetDC", 1),
        makeFunc("ReleaseDC", 2),
        makeFunc("PeekMessageA", 5),
        makeFunc("PeekMessageW", 5),
        makeFunc("GetSystemMetrics", 1),
        makeFunc("GetClientRect", 2),
        makeFunc("GetWindowRect", 2),
        makeFunc("OffsetRect", 3),
        makeFunc("UnionRect", 3),
        makeFunc("ClientToScreen", 2),
        makeFunc("ScreenToClient", 2),
        makeFunc("AdjustWindowRect", 3),
        makeFunc("FillRect", 3),
        makeFunc("InvalidateRect", 3),
        makeFunc("DrawTextA", 5),
        makeFunc("DrawTextW", 5),
        makeFunc("GetAsyncKeyState", 1),
        makeFunc("GetKeyState", 1),
        makeFunc("GetKeyboardState", 1),
        makeFunc("SetKeyboardState", 1),
        makeFunc("VkKeyScanA", 1),
        makeFunc("wsprintfA", 16, { callingConvention: "cdecl" }),
        makeFunc("wvsprintfA", 3),
        makeFunc("LoadImageA", 6),
        makeFunc("LoadImageW", 6),
        makeFunc("MapVirtualKeyA", 2),
        makeFunc("MapVirtualKeyW", 2),
        makeFunc("ToAscii", 5),
        makeFunc("ToUnicode", 6),
        makeFunc("GetKeyNameTextA", 3),
        makeFunc("GetKeyboardType", 1),
        makeFunc("GetKeyboardLayout", 1),
        makeFunc("GetKeyboardLayoutNameA", 1),
        makeFunc("GetKeyboardLayoutList", 2),
        makeFunc("ActivateKeyboardLayout", 2),
        makeFunc("UnloadKeyboardLayout", 1),
        makeFunc("keybd_event", 4),
        makeFunc("mouse_event", 5),
        makeFunc("SendInput", 3),
        makeFunc("SetLastErrorEx", 2),
        makeFunc("CharUpperA", 1),
        makeFunc("CharUpperW", 1),
        makeFunc("CharLowerA", 1),
        makeFunc("CharLowerW", 1),
        makeFunc("MoveWindow", 6),
        makeFunc("FindWindowA", 2),
        makeFunc("SetCursor", 1),
        makeFunc("SetCursorPos", 2),
        makeFunc("SetTimer", 4),
        makeFunc("KillTimer", 2),
        makeFunc("GetActiveWindow", 0),
        makeFunc("SetActiveWindow", 1),
        makeFunc("GetLastActivePopup", 1),
        makeFunc("ReleaseCapture", 0),
        makeFunc("SetCapture", 1),
        makeFunc("GetCursorPos", 1),
        makeFunc("GetWindowThreadProcessId", 2),
        makeFunc("MessageBeep", 1),
        makeFunc("GetForegroundWindow", 0),
        makeFunc("SetWindowLongA", 3),
        makeFunc("SetWindowLongW", 3),
        makeFunc("GetWindowLongA", 2),
        makeFunc("GetWindowLongW", 2),
        makeFunc("GetWindowContextHelpId", 1),
        makeFunc("SetWindowPos", 7),
        makeFunc("GetClassNameA", 3),
        makeFunc("GetClassNameW", 3),
        makeFunc("IsWindow", 1),
        makeFunc("IsWindowVisible", 1),
        makeFunc("IsRectEmpty", 1),
        makeFunc("CreateMenu", 0),
        makeFunc("CreatePopupMenu", 0),
        makeFunc("CheckMenuItem", 3),
        makeFunc("IsIconic", 1),
        makeFunc("GetMenu", 1),
        makeFunc("SetMenu", 2),
        makeFunc("GetSubMenu", 2),
        makeFunc("GetMenuItemCount", 1),
        makeFunc("GetMenuItemID", 2),
        makeFunc("ModifyMenuA", 5),
        makeFunc("ModifyMenuW", 5),
        makeFunc("AppendMenuA", 4),
        makeFunc("AppendMenuW", 4),
        makeFunc("InsertMenuA", 5),
        makeFunc("InsertMenuW", 5),
        makeFunc("ChangeMenuA", 5),
        makeFunc("ChangeMenuW", 5),
        makeFunc("RemoveMenu", 3),
        makeFunc("DrawMenuBar", 1),
        makeFunc("TrackPopupMenu", 7),
        makeFunc("TrackPopupMenuEx", 6),
        makeFunc("EnableMenuItem", 3),
        makeFunc("EnableWindow", 2),
        // Window focus / menu / cursor / text (often imported by games)
        makeFunc("SetForegroundWindow", 1),
        makeFunc("LoadMenuA", 2),
        makeFunc("LoadMenuW", 2),
        makeFunc("ShowCursor", 1),
        makeFunc("GetWindowTextA", 3),
        makeFunc("GetWindowTextW", 3),
        makeFunc("SetWindowTextA", 2),
        makeFunc("SetWindowTextW", 2),
        makeFunc("GetParent", 1),
        makeFunc("GetDesktopWindow", 0),
        makeFunc("GetWindowPlacement", 2),
        makeFunc("SetWindowPlacement", 2),
        makeFunc("IsZoomed", 1),
        makeFunc("GetWindowDC", 1),
        makeFunc("GetDialogBaseUnits", 0),
        makeFunc("MapDialogRect", 2),
        // Rect / dialog (often imported by games)
        makeFunc("IntersectRect", 3),
        makeFunc("SubtractRect", 3),
        makeFunc("CopyRect", 2),
        makeFunc("SetRect", 5),
        makeFunc("SetRectEmpty", 1),
        makeFunc("EndDialog", 2),
        makeFunc("GetDlgItem", 2),
        makeFunc("GetDlgItemInt", 4),
        makeFunc("SetDlgItemInt", 4),
        makeFunc("GetDlgItemTextA", 4),
        makeFunc("GetDlgItemTextW", 4),
        makeFunc("SetDlgItemTextA", 3),
        makeFunc("SetDlgItemTextW", 3),
        makeFunc("DialogBoxParamA", 5),
        makeFunc("DialogBoxParamW", 5),
        makeFunc("CheckDlgButton", 3),
        makeFunc("CheckRadioButton", 4),
        // Dialog directory-list helpers (the common-dialog-free file pickers of the era)
        makeFunc("DlgDirListA", 5),
        makeFunc("DlgDirListW", 5),
        makeFunc("DlgDirListComboBoxA", 5),
        makeFunc("DlgDirListComboBoxW", 5),
        makeFunc("DlgDirSelectExA", 4),
        makeFunc("DlgDirSelectExW", 4),
        makeFunc("DlgDirSelectComboBoxExA", 4),
        makeFunc("DlgDirSelectComboBoxExW", 4),
        makeFunc("IsDlgButtonChecked", 2),
        makeFunc("WinHelpA", 4),
        makeFunc("DestroyMenu", 1),
        makeFunc("PostMessageA", 4),
        makeFunc("PostMessageW", 4),
        makeFunc("PostThreadMessageA", 4),
        makeFunc("PostThreadMessageW", 4),
        makeFunc("AdjustWindowRectEx", 4),
        // Message sending (often imported by games and DLLs)
        makeFunc("SendMessageA", 4),
        makeFunc("SendMessageW", 4),
        makeFunc("InSendMessage", 0),
        makeFunc("SendNotifyMessageA", 4),
        makeFunc("CallNextHookEx", 4),
        makeFunc("SetWindowsHookExA", 4),
        makeFunc("UnhookWindowsHookEx", 1),
        // String resources
        makeFunc("LoadStringA", 4),
        makeFunc("LoadStringW", 4),
        // Window hierarchy
        makeFunc("IsChild", 2),
        // System parameters
        makeFunc("SystemParametersInfoA", 4),
        makeFunc("SystemParametersInfoW", 4),
        // Window procedure
        makeFunc("CallWindowProcA", 5),
        makeFunc("CallWindowProcW", 5),
        // Class unregistration
        makeFunc("UnregisterClassA", 2),
        makeFunc("UnregisterClassW", 2),
        // Window hierarchy/focus (imported by video codecs like smackw32)
        makeFunc("GetTopWindow", 1),
        makeFunc("GetFocus", 0),
        makeFunc("SetFocus", 1),
        makeFunc("GetWindow", 2),
        makeFunc("GetClassInfoA", 3),
        makeFunc("GetClassInfoW", 3),
        makeFunc("GetClassLongA", 2),
        makeFunc("GetClassLongW", 2),
        makeFunc("SetClassLongA", 3),
        makeFunc("SetClassLongW", 3),
        makeFunc("MsgWaitForMultipleObjects", 5),
        // Window state
        makeFunc("IsWindowEnabled", 1),
        makeFunc("IsWindowUnicode", 1),
        makeFunc("BringWindowToTop", 1),
        makeFunc("LockWindowUpdate", 1),
        // Scrolling
        makeFunc("SetScrollPos", 4),
        // Deferred window positioning
        makeFunc("BeginDeferWindowPos", 1),
        makeFunc("DeferWindowPos", 8),
        makeFunc("EndDeferWindowPos", 1),
        // Rectangle operations
        makeFunc("EqualRect", 2),
        makeFunc("PtInRect", 3), // RECT* + POINT (x, y as separate args)
        makeFunc("ValidateRect", 2),
        makeFunc("FrameRect", 3),
        makeFunc("InflateRect", 3),
        makeFunc("DrawFocusRect", 2),
        makeFunc("ExcludeUpdateRgn", 2),
        // Coordinate mapping
        makeFunc("MapWindowPoints", 4),
        // Dialog functions
        makeFunc("SendDlgItemMessageA", 5),
        makeFunc("SendDlgItemMessageW", 5),
        makeFunc("CreateDialogIndirectParamA", 5),
        makeFunc("IsDialogMessageA", 2),
        makeFunc("IsDialogMessageW", 2),
        makeFunc("GetDlgCtrlID", 1),
        makeFunc("GetNextDlgTabItem", 3),
        makeFunc("DefDlgProcA", 4),
        // Menu functions
        makeFunc("SetMenuItemBitmaps", 5),
        makeFunc("GetMenuState", 3),
        makeFunc("GetMenuCheckMarkDimensions", 0),
        makeFunc("DeleteMenu", 3),
        makeFunc("GetMenuStringA", 5),
        makeFunc("GetMenuItemInfoA", 4),
        makeFunc("GetMenuItemInfoW", 4),
        makeFunc("SetMenuItemInfoA", 4),
        // Text drawing
        makeFunc("TabbedTextOutA", 8),
        makeFunc("GrayStringA", 9),
        makeFunc("GetTabbedTextExtentA", 5),
        makeFunc("DrawTextExA", 6),
        // Window management
        makeFunc("ShowOwnedPopups", 2),
        makeFunc("GetWindowTextLengthA", 1),
        makeFunc("RedrawWindow", 4),
        // System colors
        makeFunc("GetSysColor", 1),
        makeFunc("GetSysColorBrush", 1),
        makeFunc("SetSysColors", 3),
        // Clipboard
        makeFunc("OpenClipboard", 1),
        makeFunc("CloseClipboard", 0),
        makeFunc("EmptyClipboard", 0),
        makeFunc("SetClipboardData", 2),
        makeFunc("GetClipboardData", 1),
        makeFunc("IsClipboardFormatAvailable", 1),
        makeFunc("CountClipboardFormats", 0),
        makeFunc("RegisterClipboardFormatA", 1),
        makeFunc("RegisterClipboardFormatW", 1),
        // Accelerators
        makeFunc("LoadAcceleratorsA", 2),
        makeFunc("CopyAcceleratorTableA", 3),
        makeFunc("CreateAcceleratorTableA", 2),
        makeFunc("TranslateAcceleratorA", 3),
        makeFunc("TranslateAcceleratorW", 3),
        makeFunc("DestroyAcceleratorTable", 1),
        // DDE
        makeFunc("DdeInitializeA", 4),
        makeFunc("DdeUninitialize", 1),
        makeFunc("DdeGetLastError", 1),
        makeFunc("DdeCreateStringHandleA", 3),
        makeFunc("DdeQueryStringA", 5),
        makeFunc("DdeConnect", 4),
        makeFunc("DdeDisconnect", 1),
        makeFunc("DdeClientTransaction", 8),
        makeFunc("DdeFreeStringHandle", 2),
        makeFunc("ReuseDDElParam", 5),
        makeFunc("UnpackDDElParam", 4),
        // Window properties
        makeFunc("SetPropA", 3),
        makeFunc("SetPropW", 3),
        makeFunc("GetPropA", 2),
        makeFunc("GetPropW", 2),
        makeFunc("RemovePropA", 2),
        makeFunc("RemovePropW", 2),
        // Message functions
        makeFunc("GetMessageTime", 0),
        makeFunc("GetMessagePos", 0),
        makeFunc("WaitMessage", 0),
        makeFunc("WaitForInputIdle", 2),
        makeFunc("RegisterWindowMessageA", 1),
        makeFunc("RegisterWindowMessageW", 1),
        // Caret
        makeFunc("DestroyCaret", 0),
        makeFunc("ShowCaret", 1),
        makeFunc("HideCaret", 1),
        // Mouse
        makeFunc("GetCapture", 0),
        makeFunc("ClipCursor", 1),
        makeFunc("WindowFromPoint", 2), // POINT (x, y as separate args)
        // Display settings
        makeFunc("ChangeDisplaySettingsA", 2),
        makeFunc("ChangeDisplaySettingsW", 2),
        // Resources
        makeFunc("LoadBitmapA", 2),
        // String functions
        makeFunc("CharNextA", 1),
        makeFunc("CharUpperBuffA", 2),
        // Additional user32 imports from newer runtimes/launchers
        makeFunc("PaintDesktop", 1),
        makeFunc("TabbedTextOutW", 8),
        makeFunc("DrawStateW", 10),
        makeFunc("DrawStateA", 10),
        makeFunc("GrayStringW", 9),
        makeFunc("DrawTextExW", 6),
        makeFunc("DrawIcon", 4),
        makeFunc("DrawCaption", 4),
        makeFunc("DrawFrameControl", 4),
        makeFunc("DrawEdge", 4),
        makeFunc("GetGUIThreadInfo", 2),
        makeFunc("SetWinEventHook", 7),
        makeFunc("NotifyWinEvent", 4),
        makeFunc("GetCaretBlinkTime", 0),
        makeFunc("EnumWindows", 2),
        makeFunc("WindowFromDC", 1),
        makeFunc("DisableProcessWindowsGhosting", 0),
        makeFunc("GetCursorInfo", 1),
        makeFunc("CreateCursor", 7),
        makeFunc("GetCursor", 0),
        makeFunc("GetClipCursor", 1),
        makeFunc("GetDCEx", 3),
        makeFunc("MonitorFromWindow", 2),
        makeFunc("GetIconInfo", 2),
        makeFunc("DrawIconEx", 9),
        makeFunc("CopyImage", 5),
        makeFunc("DestroyCursor", 1),
        makeFunc("GetLayeredWindowAttributes", 4),
        makeFunc("GetMonitorInfoA", 2),
        makeFunc("MonitorFromPoint", 3),
        makeFunc("MonitorFromRect", 2),
        makeFunc("SetProcessDPIAware", 0),
        makeFunc("GetMonitorInfoW", 2),
        makeFunc("IsProcessDPIAware", 0),
        makeFunc("EnumDisplaySettingsExW", 4),
        makeFunc("EnumDisplaySettingsExA", 4),
        makeFunc("EnumDisplaySettingsA", 3),
        makeFunc("EnumDisplaySettingsW", 3),
        makeFunc("EnumDisplayDevicesA", 4),
        makeFunc("EnumDisplayDevicesW", 4),
        makeFunc("ChangeDisplaySettingsExW", 5),
        makeFunc("ChangeDisplaySettingsExA", 5),
        makeFunc("GetGuiResources", 2),
        makeFunc("RegisterRawInputDevices", 3),
        // Raw input (modern WinDrv.dll, e.g. OldUnreal 227, imports these). Stubs are enough
        // to load the DLL; GetRawInputData returning 0 = "no raw input" is benign for input.
        makeFunc("GetRawInputData", 5),
        makeFunc("GetRawInputBuffer", 3),
        makeFunc("GetRawInputDeviceList", 3),
        makeFunc("GetRawInputDeviceInfoW", 4),
        makeFunc("GetRawInputDeviceInfoA", 4),
        makeFunc("GetRegisteredRawInputDevices", 3),
        makeFunc("DefRawInputProc", 3),
        makeFunc("SetWindowsHookExW", 4),
        makeFunc("MessageBoxIndirectW", 1),
        makeFunc("MessageBoxIndirectA", 1),
        makeFunc("MessageBoxExW", 5),
        makeFunc("MessageBoxExA", 5),
        makeFunc("SetMenuInfo", 2),
        makeFunc("GetMenuInfo", 2),
        makeFunc("DialogBoxIndirectParamW", 5),
        makeFunc("DialogBoxIndirectParamA", 5),
        makeFunc("CreateDialogIndirectParamW", 5),
        makeFunc("CreateDialogParamW", 5),
        makeFunc("CreateDialogParamA", 5),
        makeFunc("UpdateLayeredWindowIndirect", 2),
        makeFunc("UpdateLayeredWindow", 9),
        makeFunc("AnimateWindow", 3),
        makeFunc("GetWindowInfo", 2),
        makeFunc("GetWindowRgn", 2),
        makeFunc("GetUpdateRect", 3),
        makeFunc("GetUpdateRgn", 3),
        makeFunc("ScrollWindowEx", 8),
        makeFunc("ScrollWindow", 5),
        makeFunc("GetScrollBarInfo", 3),
        makeFunc("GetAncestor", 2),
        makeFunc("GetScrollPos", 2),
        makeFunc("SetMenuItemInfoW", 4),
        makeFunc("GetClassInfoExA", 3),
        makeFunc("GetClassInfoExW", 3),
        makeFunc("DefMDIChildProcA", 4),
        makeFunc("DefMDIChildProcW", 4),
        makeFunc("DefFrameProcA", 5),
        makeFunc("DefFrameProcW", 5),
        makeFunc("DefDlgProcW", 4),
        makeFunc("InternalGetWindowText", 3),
        makeFunc("SetLayeredWindowAttributes", 4),
        makeFunc("AttachThreadInput", 3),
        makeFunc("CopyIcon", 1),
        makeFunc("CreateIconIndirect", 1),
        makeFunc("CreateIconFromResourceEx", 7),
        makeFunc("CreateIconFromResource", 5),
        makeFunc("CreateIcon", 7),
        makeFunc("PrivateExtractIconsW", 8),
        makeFunc("PrivateExtractIconsA", 8),
        makeFunc("LoadCursorFromFileW", 1),
        makeFunc("LoadCursorFromFileA", 1),
        makeFunc("EnumDisplayMonitors", 4),
        makeFunc("EnumThreadWindows", 3),
        makeFunc("FindWindowExW", 4),
        makeFunc("FindWindowExA", 4),
        makeFunc("FindWindowW", 2),
        makeFunc("EnumChildWindows", 3),
        makeFunc("SetWindowRgn", 3),
        makeFunc("SendMessageTimeoutA", 7),
        makeFunc("SendMessageTimeoutW", 7),
        makeFunc("EnumDesktopWindows", 3),
        makeFunc("InvertRect", 2),
        makeFunc("ScrollDC", 7),
        // Hot keys
        makeFunc("RegisterHotKey", 4),
        makeFunc("UnregisterHotKey", 2),
        // Window hierarchy
        makeFunc("SetParent", 2),
        // String functions
        makeFunc("CharLowerBuffA", 2),
        makeFunc("CharToOemBuffA", 3),
        makeFunc("CharToOemA", 2),
        makeFunc("OemToCharA", 2),
        makeFunc("SwapMouseButton", 1),
        // Mouse tracking
        makeFunc("TrackMouseEvent", 1),
        // Window state
        makeFunc("OpenIcon", 1),
        makeFunc("CloseWindow", 1),
        makeFunc("ChildWindowFromPoint", 3),
        makeFunc("ChildWindowFromPointEx", 4),
        makeFunc("OpenInputDesktop", 3),
        makeFunc("CloseDesktop", 1),
        // Scroll bar
        makeFunc("EnableScrollBar", 3),
        makeFunc("SetScrollInfo", 4),
        makeFunc("GetScrollInfo", 3),
        makeFunc("SetScrollRange", 5),
        makeFunc("GetScrollRange", 4),
        makeFunc("ShowScrollBar", 3),
        // Misc often requested by wrappers
        makeFunc("PrintWindow", 3),
        makeFunc("FlashWindow", 2),
        makeFunc("FlashWindowEx", 1),
        makeFunc("DrawAnimatedRects", 4),
        makeFunc("LockSetForegroundWindow", 1),
        makeFunc("AllowSetForegroundWindow", 1),
        makeFunc("GetWindowModuleFileNameA", 3),
        makeFunc("GetWindowModuleFileNameW", 3),
        makeFunc("RealGetWindowClassA", 3),
        makeFunc("RealGetWindowClassW", 3),
        // Window text (W length)
        makeFunc("GetWindowTextLengthW", 1),
        // Props (Ex variants)
        makeFunc("EnumPropsA", 2),
        makeFunc("EnumPropsW", 2),
        makeFunc("EnumPropsExA", 3),
        makeFunc("EnumPropsExW", 3),
        // Menu (W + missing)
        makeFunc("GetMenuStringW", 5),
        makeFunc("InsertMenuItemA", 4),
        makeFunc("InsertMenuItemW", 4),
        // Misc
        makeFunc("GetNextWindow", 2),

        // Auto-generated from reference signatures
        makeFunc("CreateCaret", 4),
        makeFunc("CreateDesktopA", 6),
        makeFunc("CreateDesktopW", 6),
        makeFunc("CreateMDIWindowA", 10),
        makeFunc("CreateMDIWindowW", 10),
        makeFunc("CreateWindowStationA", 4),
        makeFunc("CreateWindowStationW", 4),
        makeFunc("DestroyIcon", 1),
        makeFunc("DrawMenuBarTemp", 5),
        makeFunc("EndMenu", 0),
        makeFunc("EndTask", 3),
        makeFunc("GetCaretPos", 1),
        makeFunc("GetClassLongPtrA", 2),
        makeFunc("GetClassLongPtrW", 2),
        makeFunc("GetClassWord", 2),
        makeFunc("GetClipboardOwner", 0),
        makeFunc("GetClipboardSequenceNumber", 0),
        makeFunc("GetClipboardViewer", 0),
        makeFunc("GetComboBoxInfo", 2),
        makeFunc("GetDoubleClickTime", 0),
        makeFunc("GetDpiForSystem", 1),
        makeFunc("GetDpiForWindow", 1),
        makeFunc("GetIconInfoExA", 2),
        makeFunc("GetIconInfoExW", 2),
        makeFunc("GetInputState", 0),
        makeFunc("GetKBCodePage", 0),
        makeFunc("GetLastInputInfo", 1),
        makeFunc("GetListBoxInfo", 1),
        makeFunc("GetMenuBarInfo", 4),
        makeFunc("GetMenuContextHelpId", 1),
        makeFunc("GetMenuDefaultItem", 3),
        makeFunc("GetMenuItemRect", 4),
        makeFunc("GetMessageExtraInfo", 0),
        makeFunc("GetNextDlgGroupItem", 3),
        makeFunc("GetOpenClipboardWindow", 0),
        makeFunc("GetProcessDefaultLayout", 1),
        makeFunc("GetQueueStatus", 1),
        makeFunc("GetShellWindow", 0),
        makeFunc("GetSystemMenu", 2),
        makeFunc("GetThreadDesktop", 1),
        makeFunc("GetTitleBarInfo", 2),
        makeFunc("GetWindowLongPtrA", 2),
        makeFunc("GetWindowLongPtrW", 2),
        makeFunc("GetWindowWord", 2),
        makeFunc("InvalidateRgn", 3),
        makeFunc("LoadAcceleratorsW", 2),
        makeFunc("LoadBitmapW", 2),
        makeFunc("LoadKeyboardLayoutA", 2),
        makeFunc("LoadKeyboardLayoutW", 2),
        makeFunc("LoadMenuIndirectA", 1),
        makeFunc("LoadMenuIndirectW", 1),
        makeFunc("MapVirtualKeyExA", 3),
        makeFunc("MapVirtualKeyExW", 3),
        makeFunc("RegisterDeviceNotificationA", 3),
        makeFunc("RegisterDeviceNotificationW", 3),
        makeFunc("UnregisterDeviceNotification", 1),
        makeFunc("RegisterLogonProcess", 2),
        makeFunc("RegisterShellHookWindow", 1),
        makeFunc("SetCaretBlinkTime", 1),
        makeFunc("SetCaretPos", 2),
        makeFunc("SetClassLongPtrA", 3),
        makeFunc("SetClassLongPtrW", 3),
        makeFunc("SetClassWord", 3),
        makeFunc("SetClipboardViewer", 1),
        makeFunc("SetDebugErrorLevel", 1),
        makeFunc("SetDeskWallPaper", 1),
        makeFunc("SetDoubleClickTime", 1),
        makeFunc("SetMenuContextHelpId", 2),
        makeFunc("SetMenuDefaultItem", 3),
        makeFunc("SetMessageExtraInfo", 1),
        makeFunc("SetMessageQueue", 1),
        makeFunc("SetProcessDefaultLayout", 1),
        makeFunc("SetProcessWindowStation", 1),
        makeFunc("SetSysColorsTemp", 3),
        makeFunc("SetSystemCursor", 2),
        makeFunc("SetSystemMenu", 2),
        makeFunc("SetSystemTimer", 4),
        makeFunc("SetThreadDesktop", 1),
        makeFunc("SetUserObjectSecurity", 3),
        makeFunc("SetWindowContextHelpId", 2),
        makeFunc("SetWindowLongPtrA", 3),
        makeFunc("SetWindowLongPtrW", 3),
        makeFunc("SetWindowsHookA", 2),
        makeFunc("SetWindowsHookW", 2),
        makeFunc("SetWindowWord", 3),
        makeFunc("ShowWindowAsync", 2),
        makeFunc("TranslateMDISysAccel", 2),
        makeFunc("wsprintfW", 3),
    ]
};
