/**
 * Session journal — turn a run into a re-runnable *.harness.ts artifact
 * ("how we got BoD to the menu" becomes code, not a memory file). Generates a
 * fluent script from a recorded step list, with an observations header from the
 * run result. Mirrors the Workflow resume model.
 */

import type { HarnessStep, HarnessRunResult } from "./types";
import { isSerializedFn } from "./types";

/** DSL methods rendered by name; anything else falls back to .call('cmd', ...). */
const NAMED_VERBS = new Set([
    "reload", "openWgb", "loadPe", "audioGesture", "streamLogs", "logs", "logStats", "markLog", "logsSince",
    "watchLog", "logCapture", "logCaptureRead", "logCaptureStop", "logAgg", "logAggStats", "waitForEvent", "waitUntil",
    "tickFrames", "watchFrames", "sleep", "click", "key", "type", "move", "drag", "wheel",
    "state", "shot", "captureFrame", "textures", "dumpTexture", "dumpSurface", "time",
    "perfProfile", "perfSpikes", "perfStats", "profilerStats",
    "breakOn", "breakOnExport", "breakOnSymbol", "breakOnApi", "watchMem", "pause", "resume",
    "fsRead", "fsList", "fsStat", "regGet", "expectDialog", "expectSurfaceNonBlack",
    "expectThread", "expectFileExists",
]);

function renderArg(a: unknown): string {
    if (isSerializedFn(a)) return a.__fn; // re-emit predicate as source so .waitUntil(fn) re-serializes it
    return JSON.stringify(a);
}

function renderStep(step: HarnessStep): string {
    const args = step.args.map(renderArg).join(", ");
    if (NAMED_VERBS.has(step.cmd)) return `  .${step.cmd}(${args})`;
    return `  .call(${JSON.stringify(step.cmd)}${args ? ", " + args : ""})`;
}

/** Emit a runnable *.harness.ts source from a step list. */
export function stepsToScript(steps: HarnessStep[], opts: { header?: string } = {}): string {
    const body = steps.map(renderStep).join("\n");
    return [
        "// Generated by the BottleShip harness journal. Re-run with:",
        "//   bun tools/harness.ts run <this-file>",
        opts.header ? opts.header.split("\n").map((l) => "// " + l).join("\n") : "",
        "",
        'import { harness } from "../../tools/harness";',
        "",
        "const result = await harness()",
        body,
        "  .run();",
        "",
        "console.log(JSON.stringify(result, null, 2));",
        "",
    ].filter((l) => l !== "").join("\n");
}

/** Build the observations header from a completed run. */
export function runResultToHeader(result: HarnessRunResult): string {
    const lines: string[] = [];
    lines.push(`run ${result.ok ? "PASSED" : "FAILED"} (${result.steps.length} steps)`);
    for (const s of result.steps) {
        lines.push(`  ${s.ok ? "✓" : "✗"} ${s.cmd}${s.label ? " [" + s.label + "]" : ""} (${Math.round(s.ms)}ms)${s.ok ? "" : " — " + (s.error?.message ?? "")}`);
    }
    if (result.error) lines.push(`aborted at step ${result.error.atStep} (${result.error.cmd}): ${result.error.message}`);
    return lines.join("\n");
}

/** Full journal: re-runnable script + observations header. */
export function runResultToJournal(steps: HarnessStep[], result: HarnessRunResult): string {
    return stepsToScript(steps, { header: runResultToHeader(result) });
}
